required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "golang.org/x/lint/golint",
]

[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.7.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "v1.2.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.1"

# [[constraint]]
#   name = "k8s.io/api"
#   version = "kubernetes-1.11.1"

# [[constraint]]
#   name = "k8s.io/apimachinery"
#   version = "kubernetes-1.11.1"


[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.3"

