required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "golang.org/x/lint/golint",
]

[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.7.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "v1.2.0"


[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.1"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.1"

#
# k8s.io/client-go dependency fixes
# taken from https://github.com/kubernetes/client-go/blob/kubernetes-1.11.1/Godeps/Godeps.json
#

[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "1ff28809256a84bb6966640ff3d0371af82ccba4"

[[override]]
  name = "github.com/docker/spdystream"
  revision = "449fdfce4d962303d702fec724ef0ad181c92528"
